### ISSUE TITLE
Action Context Item: create Event Subscriber

### ISSUE THREAD

**Issue by dominikmank** [shyim/shopware6-phpstorm-plugin#13]
Wenn ich ein Event subscriben will bin ich meistens in der Klasse oder an der Stelle wo das Event geworfen wird.

Geil wäre, wenn man da im Context Menu sagen könnte "Erstelle mir einen Event Subscriber dafür in folgendem Plugin" (oder evtl. folgendem Ordner). Das der automatisch dann die Datei anlegt und vorfüllt. (mit "getSubscribedEvents", richtigem Namespace und co) :D

**Comment by shyim** [comment]
added first iteration https://github.com/shyim/shopware6-phpstorm-plugin/commit/5c7cbb122ddf4bd04cb4f241114993f051778565
