### ISSUE TITLE
twig block extends won't work if shopware is located in vendor

### ISSUE THREAD

**Issue by dominikmank** [shyim/shopware6-phpstorm-plugin#18]
When using Shopware with the production template, it's not possible to extend a twig block. The belonging action item isn't shown.

Should be
![image](https://user-images.githubusercontent.com/7710527/135444989-7a614a48-993e-4d9b-87a9-abde3177c687.png)

but it's
![image](https://user-images.githubusercontent.com/7710527/135445043-7cef1464-caa0-4e18-914e-2d70caae69c8.png)

**Comment by shyim** [comment]
The run https://github.com/shyim/shopware6-phpstorm-plugin/actions/runs/1291989415 contains an artifact when it's complete. Can you unpack the zip and install that unpacked zip using PhpStorm?
