### ISSUE TITLE
Sort bundle name in template extension 

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware6-phpstorm-plugin#22]
When selecting bundle name to extend template, the list is not sorted. It would be great if it can be sorted alphabetically so it is easier to look.

**Comment by shyim** [comment]
nice idea. I guess you can type also while that menu is open

**Comment by shyim** [comment]
Is fixed with https://github.com/shyim/shopware6-phpstorm-plugin/commit/8f6d1977d1addce2c887d6aaae40b8585a27d0ae
