### ISSUE TITLE
Create snippets in belonging file

### ISSUE THREAD

**Issue by dominikmank** [shyim/shopware6-phpstorm-plugin#28]
Given i write a new file and fill it with non existing snippets, i want to have the possibility by an action to autogenerate an empty snippet in the belonging snippet file, so that i can fill it.

- if a file does not exist, it can be generated (but i think it can be a "must" to have an existing snippet file with the main namespace)
- nice to have: add snippet in all language snippet files too

**Comment by PheysX** [comment]
It would be cool to write your snippet {{ 'snipet'|trans }} or {{ $tc('snippet') }} and get a context menu entry to add it to a specific file. (or select multiple files). After that it opened an interface and you can write the snippet content for every selected file.

**Comment by PheysX** [comment]
Sounds nice
