### ISSUE TITLE
New Copy / Paste action in context menu

### ISSUE THREAD

**Issue by PheysX** [shyim/shopware6-phpstorm-plugin#37]
Add 2 new entries to the context menu to copy snippets.
- Copy as i18n js snippet
- Copy as symfony/i18n .twig snippet (based on the folder)

![image](https://user-images.githubusercontent.com/28557712/137502915-b6559876-2e5a-4d1b-8504-409ab42ab023.png)

### Example
![image](https://user-images.githubusercontent.com/28557712/137503667-d675cb77-aeb9-4722-87bd-3c48277593fc.png)
_There is a difference between i18n and symfony i guess._

When it needs variables, it would be great to build the structure like:

#### Twig
```
{{ $tc('tooltip.invalidEmail', 0, {
    email: ''
}) }}
```
#### Js
```
this.$tc('tooltip.invalidEmail', 0, {
    email: ''
})
```

#### Twig
```
{{ 'tooltip.invalidEmail'|trans({
    '%email%': ''
}) }}
```

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/137555889-61f649a8-e1bc-440b-852e-72b4568afbcd.png)
![image](https://user-images.githubusercontent.com/6224096/137555901-7df01cf7-8fe7-4987-bec8-ddaa3a07863b.png)

**Comment by PheysX** [comment]
Are the variables to difficult to implement or am i missing something in the commit?
