### ISSUE TITLE
Dont mark the .html part from .html.twig files in rename context

### ISSUE THREAD

**Issue by PheysX** [shyim/shopware6-phpstorm-plugin#41]
Phpstorm automatically mark the whole filename when you remane it, but its not useful for .html.twig or in general .*.twig files.

Now:
![image](https://user-images.githubusercontent.com/28557712/140892147-6c2b3197-5e3c-4c60-8ec1-90e7b7ab0c1f.png)

Better solution:
![image](https://user-images.githubusercontent.com/28557712/140892195-ff5e9f3e-0a12-4d95-b903-c3bd7e6f3e8f.png)

**Comment by mitelg** [comment]
what has this to do with this plugin? :thinking:

**Comment by PheysX** [comment]
Just nice to have in shopware context 😄

**Comment by mitelg** [comment]
imo something that should be fixed generally here https://plugins.jetbrains.com/plugin/7303-twig

**Comment by shyim** [comment]
Or just don't use this file extension it makes no different .twig or .html.twig

**Comment by PheysX** [comment]
okok
